version: "3"
services:
  glut2d-demo:
    build: .
    # WIN
    environment:
      - DISPLAY=host.docker.internal:0.0
    # LINUX
    #  -DISPLAY=:0.0 
    volumes:
      # LINUX
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/workspace
    privileged: true
    tty: true